openapi: 3.0.3

info:
  title: ErrorResponse
  description: ErrorResponse
  version: 0.1.0

paths: {}

components:
  schemas:
    ErrorResponse:
      title: ErrorResponse
      description: >-
        Standard error response format for unexpected or server-side errors
        (e.g., 500 Internal Server Error, 403 Forbidden, 401 Unauthorized, etc.).
        This is used when a more structured Problem Details response (RFC 9457)
        is not appropriate or when the error is general rather than validation-specific.
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          title: Error
          description: >-
            A short, machine-readable error code or identifier that categorizes
            the type of error. This field is stable and intended for programmatic
            handling by clients (e.g., mapping to specific error-handling logic).
            Common values include 'internal_error', 'forbidden', 'unauthorized',
            'rate_limit_exceeded', etc.
          example: forbidden

        message:
          type: string
          title: Message
          description: >-
            A human-readable summary of the error, suitable for display to end-users
            or logging. Should be clear, concise, and avoid exposing internal
            technical details or sensitive information (per security best practices).
          example: You are not authorized to access this resource

        details:
          title: Details
          description: >-
            Optional additional context or structured details about the error.
            This can include extra information useful for debugging (e.g., error
            codes from downstream systems, correlation IDs, or custom attributes).
            Use sparingly and avoid including sensitive data.
          type: object
          nullable: true
          additionalProperties: true
          example:
            correlationId: req-abc123-xyz
            timestamp: "2026-01-16T19:22:00Z"

      example:
        error: forbidden
        message: You are not authorized to access this resource
        details:
          correlationId: req-abc123-xyz

tags:
  - name: ErrorResponse
    description: ErrorResponse
