openapi: 3.1.0

info:
  title: ProblemDetailResponse
  description: ProblemDetailResponse
  version: 0.1.0

components:
  schemas:
    ProblemDetailErrorLocation:
      title: ProblemDetailErrorLocation
      description: The location on the HTTP request for which a problem has been detected. (e.g., body, query, header, path, cookie).
      type: string
      enum:
        - body
        - query
        - header
        - path
        - cookie
      examples:
        - body

    ProblemDetailErrorItem:
      title: ProblemDetailErrorItem
      description: >-
        Represents a single detailed error within a Problem Details response (RFC 9457).
        Provides granular information about what went wrong in the request, typically used
        in validation, semantic, or business-rule failures.
      type: object
      required:
        - location
        - code
        - message
        - type
      properties:
        location:
          $ref: '#/components/schemas/ProblemDetailErrorLocation'
          description: >-
            The part of the HTTP request where the error occurred (body, query, path, header, etc.).
            Helps clients quickly locate the problematic input.

        code:
          type: string
          title: Code
          description: >-
            A machine-readable error code that identifies the specific type of error.
            Should be stable and documented for programmatic handling.
            Follows the 'application/problem+json' error code pattern from RFC 9457.
          example: INVALID_LINE_NUMBER

        message:
          type: string
          title: Message
          description: >-
            A short, human-readable summary of the error suitable for display to end-users
            or in logs. Should be clear and concise (RFC 9457 recommends avoiding technical
            jargon where possible).
          example: Line number does not exist in the specified document

        type:
          type: string
          title: Type
          description: >-
            A URI reference or tag that identifies the problem type (RFC 9457 'type' field).
            Often used to categorize errors (e.g., validation, authorization, business-rule).
            When using tags instead of URIs, prefix with 'tag:' is a common convention.
          example: tag:validation-error

        field:
          title: Field
          description: >-
            The name of the specific field/property in the request that caused the error
            (when applicable). Useful for form-based or structured input validation.
          anyOf:
            - type: string
            - type: "null"
          example: taxYear

        detail:
          title: Detail
          description: >-
            A more detailed human-readable explanation of the error, providing additional
            context beyond the short message (maps to RFC 9457 'detail' field).
            May include contextual information or suggested corrections.
          anyOf:
            - type: string
            - type: "null"
          example: Line 99999 is not present in T1 General for 2024

        received:
          title: Received
          description: >-
            The actual value received by the server that caused the error
            (useful for debugging and helping clients understand what was invalid).
          anyOf:
            - type: string
            - type: "null"
          example: "99999"

        pointer:
          title: Pointer
          description: >-
            JSON Pointer (RFC 6901) to the exact location of the error within the request body
            (e.g., '#/lineNumbers/0'). Highly recommended for deep/nested validation errors
            (aligns with RFC 9457 best practices).
          anyOf:
            - type: string
            - type: "null"
          example: "#/lineNumbers/1"

        constraints:
          title: Constraints
          description: >-
            Optional object containing validation constraint violations
            (e.g., minLength, pattern, enum values). Keys are constraint names,
            values are expected values or descriptions.
            Useful for schema-based validation libraries.
          anyOf:
            - type: object
              additionalProperties: true
            - type: "null"
          example:
            minLength: 9
            pattern: ^\d{9}$

      examples:
        - code: REQUIRED_FIELD_MISSING
          detail: One of 'sin' or both 'fullLegalName' and 'birthDate' must be provided
          field: individual
          location: body
          message: Missing required identifier
          pointer: "#/identifier"
          received: ""
          type: tag:validation-error

    ProblemDetailResponse:
      title: ProblemDetailResponse
      description: Canonical model for problem details as defined by RFC-9457
      type: object
      required:
        - type
        - title
        - status
        - errors
      properties:
        type:
          type: string
          title: Type
          description: A URI reference that identifies the problem type
          example: tag:validation-errors

        title:
          type: string
          title: Title
          description: A short, human-readable summary of the problem type
          example: Bad Request

        status:
          type: integer
          title: Status
          description: A number indicating the HTTP status code generated for this occurrence of the problem
          example: 400

        detail:
          title: Detail
          description: A human-readable explanation specific to this occurrence of the problem
          anyOf:
            - type: string
            - type: "null"
          example: One or more validation errors occurred

        errors:
          type: array
          minItems: 1
          title: Errors
          description: >-
            A list of individual error occurrences found, with details and a pointer
            to the location of each
          items:
            $ref: '#/components/schemas/ProblemDetailErrorItem'

      examples:
        - detail: Invalid line numbers provided
          errors:
            - code: INVALID_LINE_NUMBER
              location: body
              message: Line number does not exist in the document
              pointer: "#/lineNumbers/0"
              received: "99999"
              type: tag:validation-error
          instance: /tax-documents/query
          status: 400
          title: Bad Request
          type: tag:validation-errors

tags:
  - name: ProblemDetailResponse
    description: ProblemDetailResponse